name: Auto Commit on Pull Request

on:
  pull_request:
    paths:
      - '**/*.txt'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          # Ensure we are on the branch associated with the pull request
          git checkout ${{ github.event.pull_request.head.ref }}

          # Commit changes
          git add .
          git commit -m "Auto commit changes to text files"

          # Push changes back to the pull request branch
          git push origin ${{ github.event.pull_request.head.ref }}
