name: Create Pull Request on Text File Addition

on:
  push:
    branches:
      - request

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for added text files
        run: |
          added_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          for file in $added_files; do
            if [[ $file == *.txt ]]; then
              echo "New text file found: $file"
              hub pull-request -b main -h request -m "Automatic Pull Request: New text file added"
              break
            fi
          done
