name: Create Pull Request on Text File Addition

on:
  push:
    branches:
      - request

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for added text files
        run: |
          added_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          for file in $added_files; do
            if [[ $file == *.txt ]]; then
              echo "New text file found: $file"

              # Set up the repository details
              repo_name=$(basename $(pwd))
              repo_owner=$(echo $GITHUB_REPOSITORY | cut -d '/' -f1)

              # Create a pull request using GitHub API
              curl -X POST \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$repo_owner/$repo_name/pulls" \
                -d '{"title": "Automatic Pull Request: New text file added", "head": "request", "base": "main", "body": "Automatic Pull Request created by GitHub Actions."}'

              break
            fi
          done
