name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for new text files
      run: |
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        for file in $changed_files; do
          if [[ $file == *.txt ]]; then
            echo "New text file found: $file"
            pr_number=$(echo "${{ github.event.before }}" | sed 's/refs\/heads\/pull\///')
            echo "Approving and merging the pull request"
            
            # Approve the pull request
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/reviews" \
              -d '{"event": "APPROVE"}'

            # Merge the pull request
            curl -X PUT \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/merge"

            echo "Merge complete"
          fi
        done
